language: ruby
rvm:
- 2.2.1
env:
  global:
    secure: nwY/Jazq6QOOh0J7i/YNgVRRY7IRSfTGNAXTcjG72htLs8R893HYbnVo6EMR9FSytM8i7Lsy2X4TuX5PSZJ0heI5BMCyoHXZqMiSyH+alqTd7XB9BJfAQ+Dd3eANW+rPZXYl+MckOsgy6O3F7prBE8asgRfXyNz29eOy6mxqe91wAAO8kWSR/xaZDlIS4DaSwIzDQ/M/+vd2M+qPDa4AGDGdFTuCe9z6JmCen/6WQrh/CsE+5ob6+EKkyLWV0xQCE65mR3EX5Re2TPmap5acxLFH8jC7YHTgHC9ftqAC9C/4Z8e1fpjPOl+5thiecx1oeG1CA1KLq6CxVjodvPiKqznJT/kdRF8t+3Deo2catA6xnzDmGZvbrvB3wWtfuj5Z/IqrdP8wcS35ZDT3ejddEb18aFeoOra7URkDHx4bjf5CX+4FS2ZABPdj+UDnryrfRCfeXnIazOREQw7yBGQH8f8QwCvWWE5kYBm6bdrKJa82FcBB8JrBX1/bDWHsZfV5KWf0cpmWUPkrgdGy/QrFykmVFSKl6lxIZq7w4mpwRn7VP8n4QTj0mPLauxcI0Yg7+vLR64iCBmprJ9M0yA9t8SwILIhuqCPjEkD27EdE/1M3B0UOFbjLJZFxNe3hI7qveAc07Uia/AjSwU92j9IsYKAlm0dqjXgZ921f0VFOLEs=
script: bundle exec rake publish